name: template
sdkPath: .fvm/flutter_sdk

packages:
  - apps/*
  - packages/cores/*
  - packages/features/*

command:
  bootstrap:
    environment:
      sdk: ^3.2.3
      flutter: ^3.16.4
    dev_dependencies:
      yumemi_lints: ^1.3.0

scripts:
  test:
    exec: flutter test --no-pub --machine > test_report.log
    packageFilters:
      flutter: true
