name: template
sdkPath: .fvm/flutter_sdk

packages:
  - packages/app
  - packages/cores/*
  - packages/features/*

command:
  bootstrap:
    environment:
      sdk: ^3.2.3
      flutter: ^3.16.4
    dev_dependencies:
      yumemi_lints: ^1.3.0
