name: cores_core
description: "This package provides core features of app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.2.3
  flutter: ^3.16.4

dependencies:
  flutter:
    sdk: flutter
  riverpod_annotation: ^2.3.3

dev_dependencies:
  build_runner: ^2.4.7
  custom_lint: ^0.5.8
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  yumemi_lints: ^1.3.0
