name: cores_navigation
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ^3.16.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  yumemi_lints: ^1.3.0

flutter:
