name: features_github_repository
description: "This package provides features for GitHub repository."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.2.3
  flutter: ^3.16.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  yumemi_lints: ^1.3.0
