name: features_setting
description: "A new Flutter package project."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.2.3
  flutter: ^3.16.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
