name: "Cleanup Copilot Settings"
description: "Cleanup "

runs:
  using: "composite"
  steps:
    - name: Install jq
      # https://github.com/dcarbone/install-jq-action
      uses: dcarbone/install-jq-action@v2.1.0

    - name: Edit Json
      run: >
        jq -n -f .vscode/settings.json |
        jq '
        ."github.copilot.enable" |= {"*": false} |
        ."github.copilot.editor.enableCodeActions" |= false |
        ."github.copilot.editor.enableAutoCompletions" |= false
        '
      shell: sh
