name: "Cleanup Copilot Settings"
description: "Cleanup "

runs:
  using: "composite"
  steps:
    - name: Install jq
      # https://github.com/dcarbone/install-jq-action
      uses: dcarbone/install-jq-action@v2.1.0

    - name: Edit Json
      run: >
        jq -n -f .vscode/settings.json |
        jq ' ${{ step.env.ENABLE }} | ${{ step.env.CODE_ACTIONS }} | ${{ step.env.AUTO_COMPLETIONS }}'
      shell: sh
      env:
        ENABLE: '."github.copilot.enable" |= {"*": false}'
        CODE_ACTIONS: '."github.copilot.editor.enableCodeActions" |= false'
        AUTO_COMPLETIONS: '."github.copilot.editor.enableAutoCompletions" |= false'
