name: Auto Assign

on:
  pull_request:
    types: [ opened, ready_for_review ]

permissions:
  pull-requests: write

jobs:
  assign:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Generate a token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID_OF_YUMEMI_TEAM_REVIEW_REQUESTER }}
          private-key: ${{ secrets.APP_PRIVATE_KEY_OF_YUMEMI_TEAM_REVIEW_REQUESTER }}
      # https://docs.github.com/ja/rest/pulls/review-requests?apiVersion=2022-11-28#request-reviewers-for-a-pull-request
      - name: Set reviewers
        run: |
          # https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=opened#pull_request
          # https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=ready_for_review#pull_request
          reviewers_count=$(cat ${{ github.event_path }} | jq '.pull_request.requested_reviewers | length')
          if [[ $reviewers_count == 0 ]]; then
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ steps.app-token.outputs.token }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers \
              -d '{"team_reviewers":["flutter_mobile_project_template"]}'
          fi
      - name: Set assignees
        uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }}
          ready-comment: 'Ready for review :rocket:'
