name: Check generated code is latest

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check:
    runs-on: ubuntu-22.04

    timeout-minutes: 10

    steps:
      - name: Setup Application Runtime
        uses: ./.github/actions/setup-application-runtime

      - name: Regenerate code
        run: melos run regenerate_code --no-select

      - name: Check difference
        run: |
          git add -N .
          git diff --name-only --exit-code
