name: Template Cleanup

on:
  workflow_dispatch: #デバッグで使用するだけなので後で削除する
  push:
    branches:
      - main

jobs:
  template-cleanup:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write

    timeout-minutes: 10
    # if: github.event.repository.name != 'flutter-mobile-project-template'
    steps:
      # https://github.com/actions/checkout
      - name: Fetch sources
        uses: actions/checkout@v4

      - name: Cleanup Copilot Settings
        uses: ./.github/actions/cleanup-copilot-settings
